name: Build downstream artifacts
on:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build-element-web:
        name: Build element-web
        uses: matrix-org/matrix-react-sdk/.github/workflows/element-web.yaml@v3.97.0
        with:
            matrix-js-sdk-sha: ${{ github.sha }}
            react-sdk-repository: matrix-org/matrix-react-sdk
