name: Sync matrix-org fork

on:
    schedule:
        - cron: "47 9 * * *" # 9:47 UTC
    workflow_dispatch: # on button click

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PAT }}
            - run: git remote add upstream https://github.com/matrix-org/matrix-js-sdk
            - run: git fetch upstream
            - run: git reset --hard upstream/develop
            - uses: peter-evans/create-pull-request@v6
              with:
                  author: GitHub <noreply@github.com>
                  branch: matrix-org-develop
                  title: Update from matrix-org upstream
                  token: ${{ secrets.PAT }}
